#toket, path and credentials

import telebot
from google.oauth2 import service_account
from googleapiclient.discovery import build


bot = telebot.TeleBot('key')  #ented your own key generated by BotFather TG
credentials_path = 'path....../service.json' #ented your path to json

#client for Google calendar api
credentials = service_account.Credentials.from_service_account_file(
    credentials_path, scopes=['https://www.googleapis.com/auth/calendar']
)
service = build('calendar', 'v3', credentials=credentials)
